# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Firebase_Auth' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Firebase_Auth
  pod 'Firebase/Auth', '~> 5.20.1'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

end
